config/routes.rb
Anime::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :episodes

  resources :series

  root :to => 'home#index'
  match 'anime/:id' => 'home#show', :as => :anime
  match 'ep/:id' => 'home#episode', :as => :ep
  match 'users' => 'users#index', :via => :get
  match 'users/:id/approve' => 'users#approve', :as => :approve_user, :via => :post

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :series
  attr_accessible :number, :series_id, :source, :title
end

app/models/series.rb
class Series < ActiveRecord::Base
  has_many :episodes
  attr_accessible :synopsis, :title, :image
  
  if Rails.env != "development"
    has_attached_file :image,
    :styles => { :medium => "282x450", :thumb => "260x180#" },
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :unique_filename => true
    }
  else
    has_attached_file :image,
    :styles => { :medium => "282x450", :thumb => "260x180#" }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :send_admin_mail
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :approved
  # attr_accessible :title, :body

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # User whatever other message
    end
  end

  def send_admin_mail
    AdminMailer.new_user_waiting_for_approval(self).deliver
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def authenticate_admin
    authenticate_user!
    if !current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_admin
  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @episodes }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episode = Episode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.json
  def new
    @episode = Episode.new
    @series = Series.find(params[:series_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
    @series = Series.find(params[:series_id])
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode.series, notice: 'Episode was successfully created.' }
        format.json { render json: @episode, status: :created, location: @episode }
      else
        format.html { render action: "new" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to @episode.series, notice: 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @series = Series.order("title ASC")
  end

  def show
    @serie = Series.find(params[:id])
    @episodes = @serie.episodes.order("number ASC")
  end

  def episode
    @episode = Episode.find(params[:id])

    ant = @episode.number - 1
    sig = @episode.number + 1
    @next = Episode.find_by_number_and_series_id(sig, @episode.series.id)
    @pre = Episode.find_by_number_and_series_id(ant, @episode.series.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_filter :authenticate_admin
  # GET /series
  # GET /series.json
  def index
    @series = Series.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @series = Series.find(params[:id])
    @episodes = @series.episodes

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/new
  # GET /series/new.json
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(params[:series])

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render json: @series, status: :created, location: @series }
      else
        format.html { render action: "new" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.json
  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_admin

  def index
    if params[:approved] == "false"
      @users = User.find_all_by_approved(false)
    else
      @users = User.all
    end
  end

  def approve
    @user = User.find(params[:id])

    @user.approved = true

    respond_to do |format|
      if @user.update_attributes(params[:user])
        AdminMailer.new_user_approved(@user).deliver
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/episodes/_form.html.erb
<%= form_for @episode, html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label 'Número Episodio', class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :number, class: 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Título', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Source (mp4)', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :source, class: 'text_field' %>
    </div>
  </div>

  <%= f.hidden_field :series_id, value: @series.id %>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', @series, class: 'btn' %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<div class="container">

<div class="page-header">
  <h1>Editando Episodio</h1>
</div>

<%= render partial: 'form' %>

</div>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Title</th>
    <th>Source</th>
    <th>Series</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.number %></td>
    <td><%= episode.title %></td>
    <td><%= episode.source %></td>
    <td><%= episode.series_id %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<div class="container">
<div class="page-header">
  <h1>Nuevo Episodio de <%= @series.title %></h1>
</div>

<%= render partial: 'form' %>

</div>

app/views/episodes/show.html.erb
<div class="container">

<div class="page-header">
  <h1>Episodio</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Serie:</strong></dt>
  <dd><%= @episode.series.title %></dd>
  <dt><strong>Título:</strong></dt>
  <dd><%= @episode.title %></dd>
  <dt><strong>Número Episodio:</strong></dt>
  <dd><%= @episode.number %></dd>
  <dt><strong>Source (mp4):</strong></dt>
  <dd><%= @episode.source %></dd>
</dl>

<video id="player_a" class="projekktor" title="PhiAnime" width="640" height="360" controls>
  <source src=<%= @episode.source %> type="video/mp4" />
</video>

<div class="form-actions">
  <%= link_to 'Volver', @episode.series, class: 'btn' %>
  <%= link_to 'Editar', edit_episode_path(@episode, series_id: @episode.series.id), class: 'btn' %>
  <%= link_to 'Eliminar', episode_path(@episode), method: 'delete', data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
</div>

</div>

app/views/home/episode.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
  <li><%= link_to @episode.series.title, anime_path(@episode.series.id) %> <span class="divider">/</span></li>
  <li class="active"><%= @episode.title %></li>
</ul>

<div class="row">
  <div class="span2"></div>
  <div class="span8">
    <div class="row">
      <div class="span1"></div>
      <div class="span6">
        <div class="navbar">
          <div class="navbar-inner">
            <ul class="nav pull-left">
              <% if @pre != nil %>
                <li><%= link_to '<', ep_path(@pre.id) %></li>
              <% end %>
            </ul>
            <ul class="nav pull-right">
              <% if @next != nil %>
                <li><%= link_to '>', ep_path(@next.id) %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="centered-text">
          <h5><%= @episode.title %></h5>
        </div>
    
        <video id="player_a" class="projekktor" title="PhiAnime" width="640" height="360" controls>
          <source src=<%= @episode.source.gsub(/mp4/, 'webm') %> type="video/webm" />
          <source src=<%= @episode.source %> type="video/mp4" />
        </video>
      </div>
      <div class="span1"></div>
    </div>
  </div>
  <div class="span2"></div>
</div>

app/views/home/index.html.erb
<ul class="breadcrumb">
  <li class="active">Home</li>
</ul>

<ul class="thumbnails">
  <% @series.each do |series| %>
    <li class="span3">
      <div class="thumbnail">
        <%= link_to (image_tag series.image.url(:thumb), :class => "img-rounded"), anime_path(series.id) %>
        <div class="caption">
          <h6><%= series.title %></h6>
        </div>
      </div>
    </li>
   <% end %>
</ul>

app/views/home/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
  <li class="active"><%= @serie.title %></li>
</ul>

<div class="row">
<div class="span6">
  <div class="centered-text"><%= image_tag @serie.image.url(:medium), :class => "img-polaroid" %></div>
</div>
<div class="span6">
  <div class="caption">
    <h3><%= @serie.title %></h3>
    <p><%= @serie.synopsis %></p>
  </div>
</div>
</div>

<table class="table table-hover">
  <thead>
    <th></th>
    <th>Capítulos</th>
  </thead>
  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><strong><%= episode.number %></strong></td>
        <td><%= link_to episode.title, ep_path(episode.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anime</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="brand">PhiAnime</div>
      <ul class="nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container">
      <%# if notice != nil %>
        <!--<div class="alert alert-info alert-block fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%#= notice %>
        </div>-->
      <%# end %>

      <%# if alert != nil %>
        <!--<div class="alert fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%#= alert %>
        </div>-->
      <%# end %>
        
      <%= yield %>
  </div>

  <script type="text/javascript">
    $(document).ready(function() {
      projekktor('#player_a', {
        <% if Rails.env == "development" %>
          playerFlashMP4: 'http://localhost:3000/assets/jarisplayer.swf',
          playerFlashMP3: 'http://localhost:3000/assets/jarisplayer.swf'
        <% else %>
          playerFlashMP4: 'http://anime.phifo.cl/assets/jarisplayer.swf',
          playerFlashMP3: 'http://anime.phifo.cl/assets/jarisplayer.swf'
        <% end %>
      });
    });
  </script>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-17734484-9']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>

app/views/series/_form.html.erb
<%= form_for @series, html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :synopsis, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :synopsis, class: 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Imagen', class: 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, class: 'file_field' %>
    </div>
  </div>

  <div class="form-actions">  
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Cancelar', series_index_path, class: 'btn' %>
  </div>
<% end %>

app/views/series/edit.html.erb
<div class="container">
<div class="page-header">
  <h1>Editar Serie</h1>
</div>

<%= render partial: 'form' %>
</div>

app/views/series/index.html.erb
<div class="container">
<ul class="breadcrumb">
  <li><%= link_to 'Home', root_path %> <span class="divider">/</span></li>
  <li class="active">Series</li>
</ul>
<div class="page-header">
  <h1>Series</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Sinopsis</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= link_to series.title, series %></td>
        <td><%= series.synopsis[0..80]+"..." %></td>
        <td>
          <%= link_to 'Editar', edit_series_path(series), :class => 'btn btn-mini' %>
          <%= link_to 'Eliminar', series, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Agregar', new_series_path, class: 'btn btn-primary' %>

</div>

app/views/series/new.html.erb
<div class="container">
<div class="page-header">
  <h1>Agregar Serie</h1>
</div>

<%= render :partial => 'form' %>
</div>

app/views/series/show.html.erb
<div class="container">

<div class="page-header">
  <h1>Serie</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Título:</strong></dt>
  <dd><%= @series.title %></dd>
  <dt><strong>Sinopsis:</strong></dt>
  <dd><%= @series.synopsis %></dd>
  <dt><strong>Imagen:</strong></dt>
  <dd><%= image_tag @series.image.url(:medium) %></dd>
</dl>

<div  class="form-actions">
  <%= link_to 'Volver', series_index_path, class: 'btn' %>
  <%= link_to 'Editar', edit_series_path(@series), class: 'btn' %>
  <%= link_to 'Eliminar', series_path(@series), method: 'delete', data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Título</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.number %></td>
        <td><%= link_to episode.title, episode %></td>
        <td>
          <%= link_to 'Editar', edit_episode_path(episode, series_id: @series.id), :class => 'btn btn-mini' %>
          <%= link_to 'Eliminar', episode, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Agregar', new_episode_path(series_id: @series.id), class: 'btn btn-primary'%>

</div>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "All Users", :action => "index" %> | <%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>

<table>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.approved %></td>
    <% if !user.approved? %>
      <td><%= link_to "Approve", approve_user_path(user), :method => :post %></td>
    <% end %>
  </tr>
  <% end %>
</table>